public enum TokenType {
    EOF,

    IMPORT,
    IF, ELSE, ELIF,

    VARIABLE, CONSTANT,
    FUNCTION, OBJECT,

    RETURN,

    TRY, CATCH, THROW,
    SWITCH, DEFAULT, CASE, SWITCH_BREAK, SWITCH_GOTO,
    FOR, OF, WHILE, LOOP_BREAK, LOOP_CONTINUE,

    L_PAREN, R_PAREN, L_CURLY_BRACE, R_CURLY_BRACE, L_BRACE, R_BRACE,
    IDENTIFIER, EQUALS,
    COMMA, MINUS_R_ANGLE_BAR, DOT, COLON, SEMICOLON,

    DOUBLE_AMPERSAND, DOUBLE_PIPE, CARAT, AMPERSAND, PIPE,
    DOUBLE_EQUALS, EXCLAMATION_EQUALS, L_ANGLE_BAR, R_ANGLE_BAR, L_ANGLE_BAR_EQUALS, R_ANGLE_BAR_EQUALS,
    DOUBLE_L_ANGLE_BAR, DOUBLE_R_ANGLE_BAR,
    PLUS, MINUS, STAR, FORWARD_SLASH, PERCENT, EXCLAMATION,
    DOUBLE_STAR, DOUBLE_PLUS, DOUBLE_MINUS,

    STRING_LITERAL, NUMBER_LITERAL, BOOLEAN_LITERAL, NULL_LITERAL,
    NUMBER_TYPE, BOOLEAN_TYPE, STRING_TYPE, VOID_TYPE
}
